import type { Metadata } from "next";
import { LegalLayout } from "@/components/legal-layout";

export const metadata: Metadata = { title: "Terms of service — Schools Compliance" };

export default function TermsPage() {
  return (
    <LegalLayout title="Terms of service" updated="22 September 2026">
      <p>
        These terms govern your use of Schools Compliance (the &ldquo;service&rdquo;), operated by Education
        Lincs (&ldquo;we&rdquo;, &ldquo;us&rdquo;). By creating an account or using the service, you agree to
        these terms on behalf of yourself and, where applicable, your school.
      </p>

      <div>
        <h2>The service</h2>
        <p>
          Schools Compliance is a self-assessment tool that helps schools track their readiness against the
          Department for Education&apos;s digital and technology standards, record supporting evidence, and
          generate progress reports. It is a working aid, not an official DfE certification or audit — you
          should always check the latest official guidance on{" "}
          <a href="https://www.gov.uk/guidance/meeting-digital-and-technology-standards-in-schools-and-colleges" target="_blank" rel="noreferrer">
            GOV.UK
          </a>{" "}
          before relying on your recorded status externally.
        </p>
      </div>

      <div>
        <h2>Accounts</h2>
        <ul>
          <li>You must provide accurate information when creating an account or a school.</li>
          <li>
            You&apos;re responsible for keeping your login credentials secure and for activity that happens
            under your account.
          </li>
          <li>Each school&apos;s admin is responsible for who they add as a user of their school&apos;s account.</li>
          <li>Tell us promptly at <a href="mailto:helpdesk@education-lincs.com">helpdesk@education-lincs.com</a> if you suspect unauthorised access to your account.</li>
        </ul>
      </div>

      <div>
        <h2>Acceptable use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the service for any unlawful purpose, or in a way that breaches any applicable law or regulation.</li>
          <li>Attempt to access another school&apos;s data, or bypass the account/permission controls in the app.</li>
          <li>Enter personal data about pupils or other third parties into the service (see our Privacy policy).</li>
          <li>Attempt to disrupt, overload, or reverse-engineer the service.</li>
        </ul>
        <p>We may suspend or remove access for accounts that breach these terms.</p>
      </div>

      <div>
        <h2>Your content</h2>
        <p>
          You (and your school) retain ownership of the compliance records, notes, and evidence links you
          enter into the service. You&apos;re responsible for the accuracy of what you record. We may use
          this data only as needed to provide the service to you, as described in our Privacy policy.
        </p>
      </div>

      <div>
        <h2>Availability</h2>
        <p>
          We aim to keep the service available and your data intact, but we don&apos;t guarantee uninterrupted
          access — the service is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis, and
          may occasionally be unavailable for maintenance or due to factors outside our control.
        </p>
      </div>

      <div>
        <h2>Liability</h2>
        <p>
          The service is a self-assessment aid, not professional or legal advice, and not an official DfE
          determination of compliance. To the fullest extent permitted by law, we&apos;re not liable for
          decisions made, or actions taken, on the basis of information recorded in or generated by the
          service. Nothing in these terms limits liability that can&apos;t lawfully be excluded, such as for
          death or personal injury caused by negligence, or fraud.
        </p>
      </div>

      <div>
        <h2>Suspension and termination</h2>
        <p>
          You can stop using the service at any time. We may suspend or close an account that breaches these
          terms, is inactive for an extended period, or where we discontinue the service, with reasonable
          notice where practical.
        </p>
      </div>

      <div>
        <h2>Changes</h2>
        <p>
          We may update these terms or the service itself from time to time. We&apos;ll update the &ldquo;last
          updated&rdquo; date above when we do; continuing to use the service after a change means you accept
          the updated terms.
        </p>
      </div>

      <div>
        <h2>Governing law</h2>
        <p>These terms are governed by the laws of England and Wales.</p>
      </div>

      <div>
        <h2>Contact</h2>
        <p>
          Education Lincs, <a href="mailto:helpdesk@education-lincs.com">helpdesk@education-lincs.com</a>
        </p>
      </div>
    </LegalLayout>
  );
}
